import { Account } from '../model/account.model';

export const accounts: Account[] = [
  {
    id: 5,
    acountName: 'Comptes Bancaires Reguliers',
    totalAccount: 0,
    isMain: false,
    isLeaf: false,
    type: 'actif',
    parentId: 1,
    path: 'actifs/Comptes Bancaires Reguliers',
  },
  {
    id: 6,
    acountName: 'Comptes Fatima',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'actif',
    parentId: 5,
    path: 'actifs/Comptes Bancaires Reguliers/Comptes Fatima',
  },
  {
    id: 7,
    acountName: 'Comptes Brahim Desjardins',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'actif',
    parentId: 5,
    path: 'actifs/Comptes Bancaires Reguliers/Comptes Brahim Desjardins',
  },

  {
    id: 8,
    acountName: 'Comptes Brahim RBC',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'actif',
    parentId: 5,
    path: 'actifs/Comptes Bancaires Reguliers/Comptes Brahim RBC',
  },
  {
    id: 9,
    acountName: 'Comptes REER',
    totalAccount: 0,
    isMain: false,
    isLeaf: false,
    type: 'actif',
    parentId: 1,
    path: 'actifs/Comptes REER',
  },

  {
    id: 10,
    acountName: 'Comptes REER Fatima',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'actif',
    parentId: 9,
    path: 'actifs/Comptes REER/Comptes REER Fatima',
  },
  {
    id: 11,
    acountName: 'Comptes REER Brahim',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'actif',
    parentId: 9,
    path: 'actifs/Comptes REER/Comptes REER Brahim',
  },
  {
    id: 12,
    acountName: 'Comptes CELI',
    totalAccount: 0,
    isMain: false,
    isLeaf: false,
    type: 'actif',
    parentId: 1,
    path: 'actifs/Comptes CELI',
  },
  {
    id: 13,
    acountName: 'Comptes CELI Fatima',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'actif',
    parentId: 12,
    path: 'actifs/Comptes CELI/Comptes CELI Fatima',
  },

  {
    id: 14,
    acountName: 'Comptes CELI Brahim',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'actif',
    parentId: 12,
    path: 'actifs/Comptes CELI/Comptes CELI Brahim',
  },
  {
    id: 15,
    acountName: 'Cash',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'actif',
    parentId: 1,
    path: 'actifs/Cash',
  },
  //expenses

  {
    id: 16,
    acountName: 'Media',
    totalAccount: 0,
    isMain: false,
    isLeaf: false,
    type: 'depense',
    parentId: 2,
    path: 'depense/Media',
  },

  {
    id: 17,
    acountName: 'Internet',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'depense',
    parentId: 16,
    path: 'depense/Media/Internet',
  },

  {
    id: 18,
    acountName: 'telephone',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'depense',
    parentId: 16,
    path: 'depense/Media/Internet',
  },
  {
    id: 19,
    acountName: 'Auto',
    totalAccount: 0,
    isMain: false,
    isLeaf: false,
    type: 'depense',
    parentId: 2,
    path: 'depense/Auto',
  },
  {
    id: 20,
    acountName: 'Gas',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'depense',
    parentId: 19,
    path: 'depense/Auto/Gas',
  },
  {
    id: 21,
    acountName: 'Soins',
    totalAccount: 0,
    isMain: false,
    isLeaf: false,
    type: 'depense',
    parentId: 2,
    path: 'depense/Soins',
  },
  {
    id: 22,
    acountName: 'Medicament',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'depense',
    parentId: 21,
    path: 'depense/Soins/Medicament',
  },
  {
    id: 23,
    acountName: 'Consultation',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'depense',
    parentId: 21,
    path: 'depense/Soins/Consultation',
  },
  {
    id: 24,
    acountName: 'Divertissements et sorties',
    totalAccount: 0,
    isMain: false,
    isLeaf: false,
    type: 'depense',
    parentId: 2,
    path: 'depense/Divertissements et sorties',
  },

  {
    id: 25,
    acountName: 'Sorties',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'depense',
    parentId: 24,
    path: 'depense/Divertissements et sorties/Sorties',
  },
  {
    id: 26,
    acountName: 'Vacances',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'depense',
    parentId: 24,
    path: 'depense/Divertissements et sorties/Vacances',
  },
  {
    id: 27,
    acountName: 'Transport',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'depense',
    parentId: 2,
    path: 'depense/Transport',
  },

  {
    id: 28,
    acountName: 'Reapair',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'depense',
    parentId: 19,
    path: 'depense/Auto/Reapair',
  },
  {
    id: 29,
    acountName: 'Assurances',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'depense',
    parentId: 19,
    path: 'depense/Auto/Assurances',
  },
  {
    id: 30,
    acountName: 'Maison',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'depense',
    parentId: 2,
    path: 'depense/Maison',
  },

  {
    id: 31,
    acountName: 'Taxes',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'depense',
    parentId: 2,
    path: 'depense/Taxes',
  },
  {
    id: 32,
    acountName: 'Groceries',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'depense',
    parentId: 2,
    path: 'depense/Groceries',
  },

  {
    id: 33,
    acountName: 'Fournitures',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'depense',
    parentId: 2,
    path: 'depense/Fournitures',
  },

  {
    id: 34,
    acountName: 'Locations',
    totalAccount: 0,
    isMain: false,
    isLeaf: false,
    type: 'depense',
    parentId: 2,
    path: 'depense/Locations',
  },
  {
    id: 35,
    acountName: 'Maison',
    totalAccount: 0,
    isMain: false,
    isLeaf: false,
    type: 'depense',
    parentId: 34,
    path: 'depense/Locations/Maison',
  },
  {
    id: 36,
    acountName: 'Education',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'depense',
    parentId: 2,
    path: 'depense/Education',
  },

  {
    id: 37,
    acountName: 'Vêtements',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'depense',
    parentId: 2,
    path: 'depense/Vêtements',
  },

  {
    id: 38,
    acountName: 'Mangé',
    totalAccount: 0,
    isMain: false,
    isLeaf: false,
    type: 'depense',
    parentId: 2,
    path: 'depense/Mangé',
  },

  {
    id: 39,
    acountName: 'Restaurants',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'depense',
    parentId: 38,
    path: 'depense/Mangé/Restaurants',
  },
  {
    id: 40,
    acountName: 'Divers',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'depense',
    parentId: 38,
    path: 'depense/Mangé/Divers',
  },
  {
    id: 41,
    acountName: 'Outils',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'depense',
    parentId: 2,
    path: 'depense/Outils',
  },
  {
    id: 42,
    acountName: 'Credit Card',
    totalAccount: 0,
    isMain: false,
    isLeaf: false,
    type: 'passif',
    parentId: 3,
    path: 'passif/Credit Card',
  },
  {
    id: 43,
    acountName: 'Credit Card Brahim',
    totalAccount: 0,
    isMain: false,
    isLeaf: false,
    type: 'passif',
    parentId: 42,
    path: 'passif/Credit Card/Credit Card Brahim',
  },
  {
    id: 44,
    acountName: 'Visa Desjardins',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'passif',
    parentId: 43,
    path: 'passif/Credit Card/Credit Card Brahim/Visa Desjardins',
  },
  {
    id: 45,
    acountName: 'CIBC Costco',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'passif',
    parentId: 43,
    path: 'passif/Credit Card/Credit Card Brahim/CIBC Costco',
  },
  {
    id: 46,
    acountName: 'MC Canadian Tire',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'passif',
    parentId: 43,
    path: 'passif/Credit Card/Credit Card Brahim/MC Canadian Tire',
  },
  {
    id: 47,
    acountName: 'Credit Card Fatima',
    totalAccount: 0,
    isMain: false,
    isLeaf: false,
    type: 'passif',
    parentId: 42,
    path: 'passif/Credit Card/Credit Card Fatima',
  },
  {
    id: 48,
    acountName: 'MC Desjardins',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'passif',
    parentId: 47,
    path: 'passif/Credit Card/Credit Card Fatima/MC Desjardins',
  },
  {
    id: 49,
    acountName: 'Prêts',
    totalAccount: 0,
    isMain: false,
    isLeaf: false,
    type: 'passif',
    parentId: 3,
    path: 'passif/Prêts',
  },

  {
    id: 50,
    acountName: 'Prêts hypothécaires',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'passif',
    parentId: 49,
    path: 'passif/Prêts/Prêts hypothécaires',
  },
  {
    id: 51,
    acountName: 'Prêts Auto',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'passif',
    parentId: 49,
    path: 'passif/Prêts/Prêts Auto',
  },
  {
    id: 52,
    acountName: 'Prêts Etudes',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'passif',
    parentId: 49,
    path: 'passif/Prêts/Prêts Etudes',
  },
  {
    id: 53,
    acountName: 'Prêts autres',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'passif',
    parentId: 49,
    path: 'passif/Prêts/Prêts autres',
  },

  {
    id: 54,
    acountName: 'Salaire fatima',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'income',
    parentId: 4,
    path: 'income/Salaire fatima',
  },
  {
    id: 55,
    acountName: 'Salaire brahim',
    totalAccount: 0,
    isMain: false,
    isLeaf: true,
    type: 'income',
    parentId: 4,
    path: 'income/Salaire brahim',
  },
];
